package edu.usca.acsc492l.flightplanner;

/**
 * Thrown whenever an exception occurs in the Airplane class
 *
 * @author Dylon Edwards
 */
public class AirplaneException extends FlightPlanException 
{
	/** The serialVersionUID generated by Eclipse */
	private static final long serialVersionUID = 0;

	/**
	 * Constructs a default AirplaneException object.
	 */
	public AirplaneException() {
		super();
	}
	
	/**
	 * Constructs a AirplaneException object with a given message.
	 * 
	 * @param message holds the AirplaneException's description
	 */
	public AirplaneException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a AirplaneException object with a given message and Throwable object
	 * 
	 * @param message holds the AirplaneException's description
	 * @param cause   holds a Throwable object to include with the AirplaneException
	 */
	public AirplaneException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a AirplaneException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the AirplaneException
	 */
	public AirplaneException(Throwable cause) {
		super(cause);
	}
}
