package edu.usca.acsc492l.flightplanner;

/**
 * Thrown when an Exception occurs in the Airport class
 *
 * @author Chris Zietlow
 * @author Dylon Edwards
 */
public class AirportException extends VertexException {

	/** Generated by the serialver utility */
	private static final long serialVersionUID = 3472491618245853149L;
	
	/**
	 * Constructs a default AirportException object.
	 */
	public AirportException() {
		super();
	}
	
	/**
	 * Constructs a AirportException object with a given message.
	 * 
	 * @param message holds the AirportException's description
	 */
	public AirportException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a AirportException object with a given message and Throwable object
	 * 
	 * @param message holds the AirportException's description
	 * @param cause   holds a Throwable object to include with the AirportException
	 */
	public AirportException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a AirportException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the AirportException
	 */
	public AirportException(Throwable cause) {
		super(cause);
	}
}
