package edu.usca.acsc492l.flightplanner;

/**
 * Thrown when an Exception occurs in the Coordinate class
 *
 * @author Chris Zietlow
 * @author Dylon Edwards
 */
public class CoordinateException extends FlightPlanException {
	
	/** Generated by the serialver utility */
	private static final long serialVersionUID = 1523992841986130171L;
	
	/**
	 * Constructs a default CoordinateException object.
	 */
	public CoordinateException() {
		super();
	}
	
	/**
	 * Constructs a CoordinateException object with a given message.
	 * 
	 * @param message holds the CoordinateException's description
	 */
	public CoordinateException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a CoordinateException object with a given message and Throwable object
	 * 
	 * @param message holds the CoordinateException's description
	 * @param cause   holds a Throwable object to include with the CoordinateException
	 */
	public CoordinateException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a CoordinateException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the CoordinateException
	 */
	public CoordinateException(Throwable cause) {
		super(cause);
	}
}
