package edu.usca.acsc492l.flightplanner;

/**
 * Thrown whenever an exception occurs in the Dijkstra class
 *
 * @author Dylon Edwards
 */
public class DijkstraException extends FlightPlanException {
	
	/** Generated by the serialver utility */
	private static final long serialVersionUID = 7129164297729433081L;
	
	/**
	 * Constructs a default DijkstraException object.
	 */
	public DijkstraException() {
		super();
	}
	
	/**
	 * Constructs a DijkstraException object with a given message.
	 * 
	 * @param message holds the DijkstraException's description
	 */
	public DijkstraException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a DijkstraException object with a given message and Throwable object
	 * 
	 * @param message holds the DijkstraException's description
	 * @param cause   holds a Throwable object to include with the DijkstraException
	 */
	public DijkstraException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a DijkstraException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the DijkstraException
	 */
	public DijkstraException(Throwable cause) {
		super(cause);
	}
}
