package edu.usca.acsc492l.flightplanner;

/**
 * Thrown whenever an exception occurs in the FlightPlan class
 *
 * @author Dylon Edwards
 */
public class FlightPlanException extends Exception {
	
	/** Generated by the serialver utility */
	private static final long serialVersionUID = 5088513151984324854L;
	
	/**
	 * Constructs a default FlightPlanException object.
	 */
	public FlightPlanException() {
		super();
	}
	
	/**
	 * Constructs a FlightPlanException object with a given message.
	 * 
	 * @param message holds the FlightPlanException's description
	 */
	public FlightPlanException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a FlightPlanException object with a given message and Throwable object
	 * 
	 * @param message holds the FlightPlanException's description
	 * @param cause   holds a Throwable object to include with the FlightPlanException
	 */
	public FlightPlanException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a FlightPlanException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the FlightPlanException
	 */
	public FlightPlanException(Throwable cause) {
		super(cause);
	}
}
