package edu.usca.acsc492l.flightplanner;

/**
 * Thrown when an Exception occurs in the NAVBeacon class
 *
 * @author Chris Zietlow
 * @author Dylon Edwards
 */
public class NAVBeaconException extends VertexException {

	/** Generated by the serialver utility */
	private static final long serialVersionUID = -6518405507117868821L;
	
	/**
	 * Constructs a default NAVBeaconException object.
	 */
	public NAVBeaconException() {
		super();
	}
	
	/**
	 * Constructs a NAVBeaconException object with a given message.
	 * 
	 * @param message holds the NAVBeaconException's description
	 */
	public NAVBeaconException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a NAVBeaconException object with a given message and Throwable object
	 * 
	 * @param message holds the NAVBeaconException's description
	 * @param cause   holds a Throwable object to include with the NAVBeaconException
	 */
	public NAVBeaconException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a NAVBeaconException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the NAVBeaconException
	 */
	public NAVBeaconException(Throwable cause) {
		super(cause);
	}
}
