package edu.usca.acsc492l.flightplanner;

/**
 * Thrown when an Exception occurs in the Runway class
 *
 * @author Chris Zietlow
 * @author Dylon Edwards
 */
public class RunwayException extends AirportException {
	
	/** Generated by the serialver utility */
	private static final long serialVersionUID = -2671074727859310556L;
	
	/**
	 * Constructs a default RunwayException object.
	 */
	public RunwayException() {
		super();
	}
	
	/**
	 * Constructs a RunwayException object with a given message.
	 * 
	 * @param message holds the RunwayException's description
	 */
	public RunwayException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a RunwayException object with a given message and Throwable object
	 * 
	 * @param message holds the RunwayException's description
	 * @param cause   holds a Throwable object to include with the RunwayException
	 */
	public RunwayException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a RunwayException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the RunwayException
	 */
	public RunwayException(Throwable cause) {
		super(cause);
	}
}
