package edu.usca.acsc492l.flightplanner;

/**
 * Thrown whenever an exception occurs in the Vertex class
 *
 * @author Dylon Edwards
 */
public class VertexException extends FlightPlanException {
	
	/** The serialVersionUID generated by Eclipse */
	private static final long serialVersionUID = 6312641721036862392L;

	/**
	 * Constructs a default VertexException object.
	 */
	public VertexException() {
		super();
	}
	
	/**
	 * Constructs a VertexException object with a given message.
	 * 
	 * @param message holds the VertexException's description
	 */
	public VertexException(String message) {
		super(message);
	}
	
	/**
	 * Constructs a VertexException object with a given message and Throwable object
	 * 
	 * @param message holds the VertexException's description
	 * @param cause   holds a Throwable object to include with the VertexException
	 */
	public VertexException(String message, Throwable cause) {
		super(message, cause);
	}
	
	/**
	 * Constructs a VertexException object with a given Throwable object
	 * 
	 * @param cause holds a Throwable object to include with the VertexException
	 */
	public VertexException(Throwable cause) {
		super(cause);
	}
}
